---

cluster_totem:
  token: 30000
  retransmits: 10
  join: 60
  consensus: 36000
  max_messages: 20

cluster_quorum:
  expected_votes: 2
  two_node: 1

# These are the default timeouts used for the SAP HANA OS clustering. Depending on the
# SAP HANA System, these may need to be adjusted if the operation takes longer than expected.
cluster_SAPHana_timeouts:
  start: 3600
  stop: 3600
  monitor_master: 700
  monitor_slave: 700
  promote: 3600
  demote: 3600

cluster_status_cmd:
  RedHat: "pcs status --full"
  Suse: "crm status full"

cluster_status_report_wait_in_s: 60

cluster_name: "db{{ hana_database.instance.sid | lower }}"
storage_object: "sbd{{ cluster_name }}"
target: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"
initiator1: "{{ iscsi_object }}.{{ hana_database.nodes[0].dbname }}.local:{{ hana_database.nodes[0].dbname }}"
initiator2: "{{ iscsi_object }}.{{ hana_database.nodes[1].dbname }}.local:{{ hana_database.nodes[1].dbname }}"
